name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule: # Every Melbourne midnight
    - cron: "0 14 * * *"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Download APKs
        run : |
          curl 'https://github.com/tlan16/revanced-build/releases/download/latest/vanced-microG.apk' -o ./fdroid/repo//vanced-microG.apk
          curl 'https://github.com/tlan16/revanced-build/releases/download/latest/revanced-nonroot.apk' -o ./fdroid/repo//vanced-microG.apk
          curl -L $(curl -s https://api.github.com/repos/M66B/FairEmail/releases/latest | grep browser_ | cut -d\" -f4) -o ./fdroid/repo/Failmail.apk
      - name: build docker image
        run: |
          docker-compose build
      - name: update metadata
        run: |
          docker-compose run fdroid update --create-metadata
      - name: deploy fdroid repo
        run: |
          docker-compose run fdroid deploy -v
      - name: Setup Pages Static Files
        run: |
          cp ./static/redirect.html ./dist/fdroid/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/fdroid'
      - name: List artifacts
        run: tree -h ./dist/fdroid
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
