name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule: # Every Melbourne midnight
    - cron: "0 14 * * *"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      - uses: suisei-cn/actions-download-file@v1.0.1
        id: download-apk  # Remember to give an ID if you need the output
        name: Download apks
        with:
          url: "https://github.com/tlan16/revanced-build/releases/download/latest/vanced-microG.apk"
          target: fdroid/repo/
          auto-match: false
      - name: build docker image
        run: |
          docker-compose build
      - name: update metadata
        run: |
          docker-compose run fdroid update --create-metadata
      - name: deploy fdroid repo
        run: |
          docker-compose run fdroid deploy -v
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/fdroid/repo'
      - name: List artifacts
        run: tree -h ./dist/fdroid/repo
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
